on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Produce archive
        id: archive
        uses: ksm2/archive-action@main
        with:
          format: 'tar.gz'
          name: 'output'
          include: 'src/*.ts'

      - name: Get the output path
        run: echo "The archive ${{ steps.archive.outputs.name }} is at ${{ steps.archive.outputs.path }} using ${{ steps.archive.outputs.media-type }}"

      - uses: actions/upload-artifact@v3
        with:
          name: Archive
          path: ${{ steps.archive.outputs.path }}
